# Generated by Django 4.1.4 on 2023-01-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_dosis_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosis',
            options={'permissions': (('can_edit_dosis', 'edit_dosis_success'),)},
        ),
    ]
