# Generated by Django 4.1.4 on 2023-01-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_dosis_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'permissions': (('can_edit_worker', 'edit_worker_success'),)},
        ),
    ]
